### ISSUE TITLE
Thoughts on Cookiecutter Data Science Integration?

### ISSUE THREAD

**Issue by hieucnguyen** [GokuMohandas/MLOps#8]
Hi Goku, I really enjoy the contents of the course! I have two questions:

1. What are your thoughts on [Cookiecutter Data Science template](https://github.com/drivendata/cookiecutter-data-science) or its variations ([pyscaffoldext-dsproject](https://github.com/pyscaffold/pyscaffoldext-dsproject), [Kedro](https://github.com/quantumblacklabs/kedro))
2. Do you plan to structure your course based on the Cookie DS template?

**Comment by GokuMohandas** [comment]
Hi @hieucnguyen, great suggestion! I have used cookiecutter templates before and I have some opinionated beliefs. I think they make a lot of sense for tooling that involves setting up a collection of sorts (ie. Great Expectations) but I personally found them too rigid, especially for opinionated areas such as data science projects. Especially because people like to organize different artifacts under various nested architectures. For example, some people like to have data in a separate folder, some versioned and never explicitly written to the project dir, some as a pointer to somewhere else (feature store, etc.). So for now, I'm just focusing on _what_ components are needed and not necessarily exactly _how_ to organize them.
